#!/bin/sh
set -efu

export HOME="$AUTOPKGTEST_TMP"

pys="$(py3versions -s 2> /dev/null)"

cp -a tests "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

for py in $pys; do
	echo "=== $py ==="
	$py -m pytest -k 'not test_application_help_6' tests -v 2>&1
done
